### ISSUE TITLE
README enhancement suggestions

### ISSUE THREAD

**Issue by dennisbirch** [nlfiedler/timedog#21]
Thanks for making this great resource available.

I have a couple of suggestions for making it easier for first-time users. 

I found that I needed to type "./timedog <parameters>" on my system to get timedog to run from Terminal. From what I just read in a StackOverflow article researching why that might be, I believe it's because I have Terminal set to use the zsh shell. I realize that as a zsh user I should know about that requirement, but in my defense I rather innocently changed from bash when I upgraded to Big Sur and was prompted to "upgrade". My point being that there are probably other people in the same boat who could use some guidance in the README to try prepending the "./" if they're using zsh.

Another README suggestion: mention the options for getting the Help screen to show. By the way, I found that -? did not work. -h and --help worked fine on my system.

Finally, either in the README or at the end of the Help screen, it would be nice to include a mention that typing "q" dismisses the Help screen and restores the Terminal to interactive mode. Having not done much in Terminal in a while I tried all sorts of other options before remembering to try "q".

**Comment by nlfiedler** [comment]
Good points, I've made changes to the readme in commit b7dc894. Note that I could not add "press q to exit" in the help because that's output through a pager (probably `more`).
